'use strict';

const envelopeSchema = {
  ok: 'boolean',
  data: 'object|null',
  error: 'object|null',
  meta: 'object',
};

const capabilities = {
  auth: {
    id: 'auth',
    summary: 'Manage SharePoint browser-session authentication',
    description: 'Authenticate with Microsoft Edge through the existing Playwright flow and inspect cached auth state.',
    verbs: {
      login: {
        id: 'auth.login',
        summary: 'Authenticate to a SharePoint site',
        method: 'AUTH',
        auth: 'none',
        handler: 'sharepoint-auth',
        params: [
          { name: 'site', type: 'string', required: true, doc: 'SharePoint site URL or host/path, for example contoso.sharepoint.com/sites/team' },
          { name: 'force', type: 'boolean', required: false, doc: 'Force visible login by passing --force' },
          { name: 'verbose', type: 'boolean', required: false, doc: 'Print per-phase progress to stderr' },
        ],
        output: { envelope: envelopeSchema, data: 'Authentication status and target site' },
        examples: ['sp-api auth login --site contoso.sharepoint.com/sites/team', 'sp-api auth login --site contoso.sharepoint.com/sites/team --verbose'],
      },
      logout: {
        id: 'auth.logout',
        summary: 'Clear the saved browser profile and auth file',
        method: 'AUTH',
        auth: 'none',
        handler: 'sharepoint-auth',
        params: [
          { name: 'site', type: 'string', required: false, doc: 'Optional SharePoint site URL for logout context' },
        ],
        output: { envelope: envelopeSchema, data: 'Logout status' },
        examples: ['sp-api auth logout'],
      },
      status: {
        id: 'auth.status',
        summary: 'Report whether cached SharePoint auth exists',
        method: 'LOCAL',
        auth: 'none',
        handler: 'auth-status',
        params: [],
        output: { envelope: envelopeSchema, data: 'Auth file location and presence' },
        examples: ['sp-api auth status'],
      },
    },
  },
  lists: {
    id: 'lists',
    summary: 'Work with SharePoint lists and list items',
    description: 'List discovery, list metadata, list creation/deletion, and item CRUD.',
    verbs: {
      list: {
        id: 'lists.list',
        summary: 'List visible SharePoint lists and libraries',
        method: 'GET',
        path: "_api/web/lists?$filter=Hidden eq false&$select=Id,Title,BaseTemplate,ItemCount",
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [],
        output: { envelope: envelopeSchema, data: 'SharePoint list collection' },
        examples: ['sp-api lists list'],
      },
      get: {
        id: 'lists.get',
        summary: 'Get metadata for one list by title or id',
        method: 'GET',
        path: "_api/web/lists/getbytitle('{title}')?$select=Id,Title,BaseTemplate,ItemCount,ListItemEntityTypeFullName",
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [
          { name: 'title', type: 'string', required: true, doc: 'List title' },
        ],
        output: { envelope: envelopeSchema, data: 'List metadata' },
        examples: ['sp-api lists get --title Tasks'],
      },
      fields: {
        id: 'lists.fields',
        summary: 'List visible fields and schema details for one list',
        method: 'GET',
        path: "_api/web/lists/getbytitle('{title}')/fields?$filter=Hidden eq false",
        query: { '$select': 'InternalName,Title,TypeAsString,Required,ReadOnlyField,Choices' },
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [
          { name: 'title', type: 'string', required: true, doc: 'List title' },
        ],
        output: { envelope: envelopeSchema, data: 'Visible list fields with internal names, types, required/read-only flags, and choices' },
        examples: ['sp-api lists fields --title Tasks'],
      },
      create: {
        id: 'lists.create',
        summary: 'Create a SharePoint list',
        method: 'POST',
        path: '_api/web/lists',
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'title', type: 'string', required: true, doc: 'New list title' },
          { name: 'template', type: 'number', required: false, default: 100, doc: 'SharePoint list template id. 100 is generic list, 101 is document library' },
        ],
        bodyTemplate: { __metadata: { type: 'SP.List' }, BaseTemplate: '{template}', Title: '{title}' },
        output: { envelope: envelopeSchema, data: 'Created list metadata' },
        examples: ['sp-api lists create --title "Project Tracker"'],
      },
      delete: {
        id: 'lists.delete',
        summary: 'Delete a SharePoint list by title',
        method: 'DELETE',
        path: "_api/web/lists/getbytitle('{title}')",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'title', type: 'string', required: true, doc: 'List title' },
        ],
        output: { envelope: envelopeSchema, data: 'Delete status' },
        examples: ['sp-api lists delete --title "Old Tracker"'],
      },
      items: {
        id: 'lists.items',
        summary: 'List items from a SharePoint list',
        method: 'GET',
        path: "_api/web/lists/getbytitle('{title}')/items",
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [
          { name: 'title', type: 'string', required: true, doc: 'List title' },
          { name: 'select', type: 'string', required: false, doc: 'Comma-separated OData $select fields' },
          { name: 'top', type: 'number', required: false, default: 100, doc: 'Maximum item count' },
        ],
        query: { '$select': '{select}', '$top': '{top}' },
        output: { envelope: envelopeSchema, data: 'List item collection' },
        examples: ['sp-api lists items --title Tasks --select Title,Id,Status --top 25'],
      },
      'add-item': {
        id: 'lists.add-item',
        summary: 'Create a list item',
        method: 'POST',
        path: "_api/web/lists/getbytitle('{title}')/items",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'title', type: 'string', required: true, doc: 'List title' },
          { name: 'body', type: 'json', required: true, doc: 'JSON item body including __metadata.type when required by the list' },
        ],
        output: { envelope: envelopeSchema, data: 'Created item metadata' },
        examples: ['sp-api lists add-item --title Tasks --body \'{"Title":"New task"}\''],
      },
      'update-item': {
        id: 'lists.update-item',
        summary: 'Update a list item',
        method: 'PATCH',
        path: "_api/web/lists/getbytitle('{title}')/items({item-id})",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'title', type: 'string', required: true, doc: 'List title' },
          { name: 'item-id', type: 'number', required: true, doc: 'List item id' },
          { name: 'body', type: 'json', required: true, doc: 'JSON item body with fields to update' },
        ],
        output: { envelope: envelopeSchema, data: 'Update status' },
        examples: ['sp-api lists update-item --title Tasks --item-id 42 --body \'{"Status":"Done"}\''],
      },
      'delete-item': {
        id: 'lists.delete-item',
        summary: 'Delete a list item',
        method: 'DELETE',
        path: "_api/web/lists/getbytitle('{title}')/items({item-id})",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'title', type: 'string', required: true, doc: 'List title' },
          { name: 'item-id', type: 'number', required: true, doc: 'List item id' },
        ],
        output: { envelope: envelopeSchema, data: 'Delete status' },
        examples: ['sp-api lists delete-item --title Tasks --item-id 42'],
      },
    },
  },
  files: {
    id: 'files',
    summary: 'Work with SharePoint files and folders',
    description: 'List folders, upload/download files, and move/copy/delete files.',
    verbs: {
      list: {
        id: 'files.list',
        summary: 'List files in a folder by server-relative path',
        method: 'GET',
        path: "_api/web/getfolderbyserverrelativeurl('{folder}')/Files",
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [
          { name: 'folder', type: 'string', required: true, doc: 'Server-relative folder path' },
        ],
        output: { envelope: envelopeSchema, data: 'Folder file collection' },
        examples: ['sp-api files list --folder "/sites/team/Shared Documents"'],
      },
      get: {
        id: 'files.get',
        summary: 'Get file metadata',
        method: 'GET',
        path: "_api/web/getfilebyserverrelativeurl('{path}')",
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative file path' },
        ],
        output: { envelope: envelopeSchema, data: 'File metadata' },
        examples: ['sp-api files get --path "/sites/team/Shared Documents/doc.txt"'],
      },
      download: {
        id: 'files.download',
        summary: 'Download file content',
        method: 'GET',
        path: "_api/web/getfilebyserverrelativeurl('{path}')/$value",
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative file path' },
          { name: 'out', type: 'string', required: false, doc: 'Local output path for binary-safe file writing' },
        ],
        output: { envelope: envelopeSchema, data: 'File content string, or write metadata when --out is provided' },
        examples: [
          'sp-api files download --path "/sites/team/Shared Documents/doc.txt"',
          'sp-api files download --path "/sites/team/Shared Documents/image.png" --out image.png',
        ],
      },
      upload: {
        id: 'files.upload',
        summary: 'Upload small text content to a folder',
        method: 'POST',
        path: "_api/web/getfolderbyserverrelativeurl('{folder}')/Files/add(url='{name}',overwrite={overwrite})",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        contentType: 'text/plain;charset=utf-8',
        bodyParam: 'content',
        requiresOneOf: [['content', 'content-file']],
        params: [
          { name: 'folder', type: 'string', required: true, doc: 'Server-relative destination folder path' },
          { name: 'name', type: 'string', required: true, doc: 'Destination file name' },
          { name: 'content', type: 'string', required: false, doc: 'Text content to upload' },
          { name: 'content-file', type: 'file-text', required: false, mapsTo: 'content', doc: 'UTF-8 text file whose contents should be uploaded' },
          { name: 'overwrite', type: 'boolean', required: false, default: true, doc: 'Whether SharePoint can overwrite an existing file' },
        ],
        output: { envelope: envelopeSchema, data: 'Uploaded file metadata' },
        examples: [
          'sp-api files upload --folder "/sites/team/Shared Documents" --name notes.txt --content "hello"',
          'sp-api files upload --folder "/sites/team/Shared Documents" --name notes.txt --content-file notes.txt',
        ],
      },
      'create-folder': {
        id: 'files.create-folder',
        summary: 'Create a folder by server-relative path',
        method: 'POST',
        path: '_api/web/folders',
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        bodyTemplate: { __metadata: { type: 'SP.Folder' }, ServerRelativeUrl: '{path}' },
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative folder path to create' },
        ],
        output: { envelope: envelopeSchema, data: 'Created folder metadata' },
        examples: ['sp-api files create-folder --path "/sites/team/Shared Documents/New Folder"'],
      },
      'delete-folder': {
        id: 'files.delete-folder',
        summary: 'Delete a folder by server-relative path',
        method: 'DELETE',
        path: "_api/web/getfolderbyserverrelativeurl('{path}')",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        notFoundOkParam: 'missing-ok',
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative folder path to delete' },
          { name: 'missing-ok', type: 'boolean', required: false, default: false, doc: 'Treat a missing folder as a successful no-op' },
        ],
        output: { envelope: envelopeSchema, data: 'Delete status' },
        examples: ['sp-api files delete-folder --path "/sites/team/Shared Documents/Old Folder" --missing-ok true'],
      },
      'recycle-folder': {
        id: 'files.recycle-folder',
        summary: 'Recycle a folder by server-relative path',
        method: 'POST',
        path: "_api/web/getfolderbyserverrelativeurl('{path}')/recycle",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        notFoundOkParam: 'missing-ok',
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative folder path to recycle' },
          { name: 'missing-ok', type: 'boolean', required: false, default: false, doc: 'Treat a missing folder as a successful no-op' },
        ],
        output: { envelope: envelopeSchema, data: 'Recycle operation result' },
        examples: ['sp-api files recycle-folder --path "/sites/team/Shared Documents/Old Folder" --missing-ok true'],
      },
      delete: {
        id: 'files.delete',
        summary: 'Delete a file',
        method: 'DELETE',
        path: "_api/web/getfilebyserverrelativeurl('{path}')",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative file path' },
        ],
        output: { envelope: envelopeSchema, data: 'Delete status' },
        examples: ['sp-api files delete --path "/sites/team/Shared Documents/old.txt"'],
      },
      move: {
        id: 'files.move',
        summary: 'Move a file',
        method: 'POST',
        path: "_api/web/getfilebyserverrelativeurl('{path}')/moveto(newurl='{destination}',flags={flags})",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative source file path' },
          { name: 'destination', type: 'string', required: true, doc: 'Server-relative destination file path' },
          { name: 'flags', type: 'number', required: false, default: 1, doc: 'SharePoint move flags. 1 overwrites, 0 fails on conflict' },
        ],
        output: { envelope: envelopeSchema, data: 'Move status' },
        examples: ['sp-api files move --path "/sites/team/Shared Documents/a.txt" --destination "/sites/team/Shared Documents/b.txt"'],
      },
      copy: {
        id: 'files.copy',
        summary: 'Copy a file',
        method: 'POST',
        path: "_api/web/getfilebyserverrelativeurl('{path}')/copyto(strnewurl='{destination}',boverwrite={overwrite})",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative source file path' },
          { name: 'destination', type: 'string', required: true, doc: 'Server-relative destination file path' },
          { name: 'overwrite', type: 'boolean', required: false, default: true, doc: 'Whether SharePoint can overwrite an existing file' },
        ],
        output: { envelope: envelopeSchema, data: 'Copy status' },
        examples: ['sp-api files copy --path "/sites/team/Shared Documents/a.txt" --destination "/sites/team/Shared Documents/copy.txt"'],
      },
      folder: {
        id: 'files.folder',
        summary: 'List folders and files under a folder',
        method: 'GET',
        path: "_api/web/getfolderbyserverrelativeurl('{folder}')",
        query: { '$expand': 'Folders,Files' },
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [
          { name: 'folder', type: 'string', required: true, doc: 'Server-relative folder path' },
        ],
        output: { envelope: envelopeSchema, data: 'Folder metadata expanded with child folders and files' },
        examples: ['sp-api files folder --folder "/sites/team/Shared Documents"'],
      },
      recycle: {
        id: 'files.recycle',
        summary: 'Recycle a file without permanently deleting it',
        method: 'POST',
        path: "_api/web/getfilebyserverrelativeurl('{path}')/recycle",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative file path' },
        ],
        output: { envelope: envelopeSchema, data: 'Recycle operation result' },
        examples: ['sp-api files recycle --path "/sites/team/Shared Documents/old.txt"'],
      },
    },
  },
  search: {
    id: 'search',
    summary: 'Search SharePoint content',
    description: 'Run bounded SharePoint search queries with explicit query text and result shaping.',
    verbs: {
      query: {
        id: 'search.query',
        summary: 'Run a SharePoint search query',
        method: 'GET',
        path: '_api/search/query',
        query: {
          querytext: "'{query}'",
          rowlimit: '{row-limit}',
          selectproperties: '{select-properties}',
        },
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [
          { name: 'query', type: 'string', required: true, doc: 'KQL query text' },
          { name: 'row-limit', type: 'number', required: false, default: 25, doc: 'Maximum search results to return' },
          { name: 'select-properties', type: 'string', required: false, doc: 'Comma-separated managed properties to return, for example Title,Path,LastModifiedTime' },
        ],
        output: { envelope: envelopeSchema, data: 'SharePoint search query result' },
        examples: ['sp-api search query --query "Project Apollo" --row-limit 10 --select-properties Title,Path'],
      },
    },
  },
  sites: {
    id: 'sites',
    summary: 'Discover SharePoint site metadata',
    description: 'Read site-level metadata that agents need before choosing list, file, page, or permission commands.',
    verbs: {
      get: {
        id: 'sites.get',
        summary: 'Get current site metadata',
        method: 'GET',
        path: '_api/web?$select=Title,Url,Description,Id,WebTemplate,Created,LastItemModifiedDate',
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [],
        output: { envelope: envelopeSchema, data: 'Current SharePoint site metadata' },
        examples: ['sp-api sites get'],
      },
      discovery: {
        id: 'sites.discovery',
        summary: 'List visible site containers for planning follow-up commands',
        method: 'GET',
        path: "_api/web/lists?$filter=Hidden eq false",
        query: { '$select': 'Id,Title,BaseTemplate,BaseType,ItemCount,RootFolder/ServerRelativeUrl', '$expand': 'RootFolder' },
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [],
        output: { envelope: envelopeSchema, data: 'Visible lists and libraries with root folder paths for site discovery' },
        examples: ['sp-api sites discovery'],
      },
    },
  },
  pages: {
    id: 'pages',
    summary: 'Work with SharePoint site pages',
    description: 'Read and manage Site Pages through semantic page verbs. Use server-relative paths for file-lifecycle verbs and item ids for field updates.',
    verbs: {
      list: {
        id: 'pages.list',
        summary: 'List modern site pages',
        method: 'GET',
        path: "_api/web/lists/getbytitle('Site Pages')/items",
        query: { '$filter': 'FSObjType eq 0', '$select': 'Id,Title,FileRef,FileLeafRef,Modified,PromotedState,CanvasContent1', '$orderby': 'FileLeafRef' },
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [],
        output: { envelope: envelopeSchema, data: 'Site Pages list items' },
        examples: ['sp-api pages list'],
      },
      get: {
        id: 'pages.get',
        summary: 'Get page fields and canvas content by server-relative path',
        method: 'GET',
        path: "_api/web/getfilebyserverrelativeurl('{path}')/ListItemAllFields",
        query: { '$select': 'Id,Title,FileRef,Modified,PromotedState,CanvasContent1,BannerImageUrl,Description' },
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative page path, for example /sites/team/SitePages/Home.aspx' },
        ],
        output: { envelope: envelopeSchema, data: 'Page list item fields and canvas content' },
        examples: ['sp-api pages get --path "/sites/team/SitePages/Home.aspx"'],
      },
      checkout: {
        id: 'pages.checkout',
        summary: 'Check out a page file',
        method: 'POST',
        path: "_api/web/getfilebyserverrelativeurl('{path}')/checkout",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative page path' },
        ],
        output: { envelope: envelopeSchema, data: 'Checkout result' },
        examples: ['sp-api pages checkout --path "/sites/team/SitePages/Home.aspx"'],
      },
      'save-fields': {
        id: 'pages.save-fields',
        summary: 'Update Site Pages list item fields by item id',
        method: 'PATCH',
        path: "_api/web/lists/getbytitle('Site Pages')/items({item-id})",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'item-id', type: 'number', required: true, doc: 'Site Pages list item id' },
          { name: 'body', type: 'json', required: true, doc: 'JSON object of page fields to update, such as Title, Description, BannerImageUrl, or CanvasContent1' },
        ],
        output: { envelope: envelopeSchema, data: 'Page field update status' },
        examples: ['sp-api pages save-fields --item-id 42 --body \'{"Title":"New title"}\''],
      },
      publish: {
        id: 'pages.publish',
        summary: 'Publish a checked-in page file',
        method: 'POST',
        path: "_api/web/getfilebyserverrelativeurl('{path}')/publish(comment='{comment}')",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative page path' },
          { name: 'comment', type: 'string', required: false, default: '', doc: 'Publish comment' },
        ],
        output: { envelope: envelopeSchema, data: 'Publish result' },
        examples: ['sp-api pages publish --path "/sites/team/SitePages/Home.aspx" --comment "Published by sp-api"'],
      },
      'discard-checkout': {
        id: 'pages.discard-checkout',
        summary: 'Discard a page checkout',
        method: 'POST',
        path: "_api/web/getfilebyserverrelativeurl('{path}')/undocheckout",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative page path' },
        ],
        output: { envelope: envelopeSchema, data: 'Discard checkout result' },
        examples: ['sp-api pages discard-checkout --path "/sites/team/SitePages/Home.aspx"'],
      },
    },
  },
  permissions: {
    id: 'permissions',
    summary: 'Inspect SharePoint permissions',
    description: 'Read web-level role assignments without granting, revoking, or breaking inheritance.',
    verbs: {
      get: {
        id: 'permissions.get',
        summary: 'Get web role assignments',
        method: 'GET',
        path: '_api/web/roleassignments',
        query: { '$expand': 'Member,RoleDefinitionBindings' },
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [],
        output: { envelope: envelopeSchema, data: 'Web role assignments expanded with members and role definition bindings' },
        examples: ['sp-api permissions get'],
      },
    },
  },
  schema: {
    id: 'schema',
    summary: 'Inspect the generated SharePoint capability schema',
    description: 'Return the machine-readable contract that also generates help and the skill router.',
    verbs: {
      show: {
        id: 'schema.show',
        summary: 'Show all capabilities or one capability/verb contract',
        method: 'LOCAL',
        auth: 'none',
        handler: 'schema',
        params: [
          { name: 'capability', type: 'string', required: false, doc: 'Capability id, for example lists or files' },
          { name: 'verb', type: 'string', required: false, doc: 'Verb id within the capability' },
        ],
        output: { envelope: envelopeSchema, data: 'Capability schema' },
        examples: ['sp-api schema', 'sp-api schema lists add-item'],
      },
    },
  },
  doctor: {
    id: 'doctor',
    summary: 'Run local health checks for the agentic CLI',
    description: 'Verify Node.js compatibility and the cached auth file.',
    verbs: {
      run: {
        id: 'doctor.run',
        summary: 'Run health checks',
        method: 'LOCAL',
        auth: 'none',
        handler: 'doctor',
        params: [],
        output: { envelope: envelopeSchema, data: 'Health-check results' },
        examples: ['sp-api doctor'],
      },
    },
  },
  update: {
    id: 'update',
    summary: 'Self-update this sp-api checkout',
    description: 'Pull latest source, install dependencies, and run the build validation for git-clone installs.',
    verbs: {
      run: {
        id: 'update.run',
        summary: 'Self-update from the current git clone',
        method: 'LOCAL',
        auth: 'none',
        handler: 'self-update',
        params: [],
        output: { envelope: envelopeSchema, data: 'Update steps and status' },
        examples: ['sp-api update'],
      },
    },
  },
};

const plannedCapabilities = {
  search: ['people'],
  pages: ['create', 'delete'],
  users: ['list', 'get', 'me', 'ensure'],
  permissions: ['grant', 'revoke', 'break-inheritance', 'reset-inheritance'],
  sites: ['subsites', 'navigation'],
};

module.exports = { capabilities, plannedCapabilities, envelopeSchema };
