'use strict';

const envelopeSchema = {
  ok: 'boolean',
  data: 'object|null',
  error: 'object|null',
  meta: 'object',
};

const capabilities = {
  auth: {
    id: 'auth',
    summary: 'Manage SharePoint browser-session authentication',
    description: 'Authenticate with Microsoft Edge through the existing Playwright flow and inspect cached auth state.',
    verbs: {
      login: {
        id: 'auth.login',
        summary: 'Authenticate to a SharePoint site',
        method: 'AUTH',
        auth: 'none',
        handler: 'sharepoint-auth',
        params: [
          { name: 'site', type: 'string', required: true, doc: 'SharePoint site URL or host/path, for example contoso.sharepoint.com/sites/team' },
          { name: 'force', type: 'boolean', required: false, doc: 'Force visible login by passing --force' },
        ],
        output: { envelope: envelopeSchema, data: 'Authentication status and target site' },
        examples: ['sp-api auth login --site contoso.sharepoint.com/sites/team'],
      },
      logout: {
        id: 'auth.logout',
        summary: 'Clear the saved browser profile and auth file',
        method: 'AUTH',
        auth: 'none',
        handler: 'sharepoint-auth',
        params: [
          { name: 'site', type: 'string', required: false, doc: 'Optional SharePoint site URL for logout context' },
        ],
        output: { envelope: envelopeSchema, data: 'Logout status' },
        examples: ['sp-api auth logout'],
      },
      status: {
        id: 'auth.status',
        summary: 'Report whether cached SharePoint auth exists',
        method: 'LOCAL',
        auth: 'none',
        handler: 'auth-status',
        params: [],
        output: { envelope: envelopeSchema, data: 'Auth file location and presence' },
        examples: ['sp-api auth status'],
      },
    },
  },
  lists: {
    id: 'lists',
    summary: 'Work with SharePoint lists and list items',
    description: 'List discovery, list metadata, list creation/deletion, and item CRUD.',
    verbs: {
      list: {
        id: 'lists.list',
        summary: 'List visible SharePoint lists and libraries',
        method: 'GET',
        path: "_api/web/lists?$filter=Hidden eq false&$select=Id,Title,BaseTemplate,ItemCount",
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [],
        output: { envelope: envelopeSchema, data: 'SharePoint list collection' },
        examples: ['sp-api lists list'],
      },
      get: {
        id: 'lists.get',
        summary: 'Get metadata for one list by title or id',
        method: 'GET',
        path: "_api/web/lists/getbytitle('{title}')?$select=Id,Title,BaseTemplate,ItemCount,ListItemEntityTypeFullName",
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [
          { name: 'title', type: 'string', required: true, doc: 'List title' },
        ],
        output: { envelope: envelopeSchema, data: 'List metadata' },
        examples: ['sp-api lists get --title Tasks'],
      },
      create: {
        id: 'lists.create',
        summary: 'Create a SharePoint list',
        method: 'POST',
        path: '_api/web/lists',
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'title', type: 'string', required: true, doc: 'New list title' },
          { name: 'template', type: 'number', required: false, default: 100, doc: 'SharePoint list template id. 100 is generic list, 101 is document library' },
        ],
        bodyTemplate: { __metadata: { type: 'SP.List' }, BaseTemplate: '{template}', Title: '{title}' },
        output: { envelope: envelopeSchema, data: 'Created list metadata' },
        examples: ['sp-api lists create --title "Project Tracker"'],
      },
      delete: {
        id: 'lists.delete',
        summary: 'Delete a SharePoint list by title',
        method: 'DELETE',
        path: "_api/web/lists/getbytitle('{title}')",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'title', type: 'string', required: true, doc: 'List title' },
        ],
        output: { envelope: envelopeSchema, data: 'Delete status' },
        examples: ['sp-api lists delete --title "Old Tracker"'],
      },
      items: {
        id: 'lists.items',
        summary: 'List items from a SharePoint list',
        method: 'GET',
        path: "_api/web/lists/getbytitle('{title}')/items",
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [
          { name: 'title', type: 'string', required: true, doc: 'List title' },
          { name: 'select', type: 'string', required: false, doc: 'Comma-separated OData $select fields' },
          { name: 'top', type: 'number', required: false, default: 100, doc: 'Maximum item count' },
        ],
        query: { '$select': '{select}', '$top': '{top}' },
        output: { envelope: envelopeSchema, data: 'List item collection' },
        examples: ['sp-api lists items --title Tasks --select Title,Id,Status --top 25'],
      },
      'add-item': {
        id: 'lists.add-item',
        summary: 'Create a list item',
        method: 'POST',
        path: "_api/web/lists/getbytitle('{title}')/items",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'title', type: 'string', required: true, doc: 'List title' },
          { name: 'body', type: 'json', required: true, doc: 'JSON item body including __metadata.type when required by the list' },
        ],
        output: { envelope: envelopeSchema, data: 'Created item metadata' },
        examples: ['sp-api lists add-item --title Tasks --body \'{"Title":"New task"}\''],
      },
      'update-item': {
        id: 'lists.update-item',
        summary: 'Update a list item',
        method: 'PATCH',
        path: "_api/web/lists/getbytitle('{title}')/items({item-id})",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'title', type: 'string', required: true, doc: 'List title' },
          { name: 'item-id', type: 'number', required: true, doc: 'List item id' },
          { name: 'body', type: 'json', required: true, doc: 'JSON item body with fields to update' },
        ],
        output: { envelope: envelopeSchema, data: 'Update status' },
        examples: ['sp-api lists update-item --title Tasks --item-id 42 --body \'{"Status":"Done"}\''],
      },
      'delete-item': {
        id: 'lists.delete-item',
        summary: 'Delete a list item',
        method: 'DELETE',
        path: "_api/web/lists/getbytitle('{title}')/items({item-id})",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'title', type: 'string', required: true, doc: 'List title' },
          { name: 'item-id', type: 'number', required: true, doc: 'List item id' },
        ],
        output: { envelope: envelopeSchema, data: 'Delete status' },
        examples: ['sp-api lists delete-item --title Tasks --item-id 42'],
      },
    },
  },
  files: {
    id: 'files',
    summary: 'Work with SharePoint files and folders',
    description: 'List folders, upload/download files, and move/copy/delete files.',
    verbs: {
      list: {
        id: 'files.list',
        summary: 'List files in a folder by server-relative path',
        method: 'GET',
        path: "_api/web/getfolderbyserverrelativeurl('{folder}')/Files",
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [
          { name: 'folder', type: 'string', required: true, doc: 'Server-relative folder path' },
        ],
        output: { envelope: envelopeSchema, data: 'Folder file collection' },
        examples: ['sp-api files list --folder "/sites/team/Shared Documents"'],
      },
      get: {
        id: 'files.get',
        summary: 'Get file metadata',
        method: 'GET',
        path: "_api/web/getfilebyserverrelativeurl('{path}')",
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative file path' },
        ],
        output: { envelope: envelopeSchema, data: 'File metadata' },
        examples: ['sp-api files get --path "/sites/team/Shared Documents/doc.txt"'],
      },
      download: {
        id: 'files.download',
        summary: 'Download file content',
        method: 'GET',
        path: "_api/web/getfilebyserverrelativeurl('{path}')/$value",
        auth: 'required',
        handler: 'sharepoint-rest',
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative file path' },
        ],
        output: { envelope: envelopeSchema, data: 'File content as returned by SharePoint' },
        examples: ['sp-api files download --path "/sites/team/Shared Documents/doc.txt"'],
      },
      upload: {
        id: 'files.upload',
        summary: 'Upload small text content to a folder',
        method: 'POST',
        path: "_api/web/getfolderbyserverrelativeurl('{folder}')/Files/add(url='{name}',overwrite={overwrite})",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'folder', type: 'string', required: true, doc: 'Server-relative destination folder path' },
          { name: 'name', type: 'string', required: true, doc: 'Destination file name' },
          { name: 'content', type: 'string', required: true, doc: 'Text content to upload' },
          { name: 'overwrite', type: 'boolean', required: false, default: true, doc: 'Whether SharePoint can overwrite an existing file' },
        ],
        output: { envelope: envelopeSchema, data: 'Uploaded file metadata' },
        examples: ['sp-api files upload --folder "/sites/team/Shared Documents" --name notes.txt --content "hello"'],
      },
      delete: {
        id: 'files.delete',
        summary: 'Delete a file',
        method: 'DELETE',
        path: "_api/web/getfilebyserverrelativeurl('{path}')",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative file path' },
        ],
        output: { envelope: envelopeSchema, data: 'Delete status' },
        examples: ['sp-api files delete --path "/sites/team/Shared Documents/old.txt"'],
      },
      move: {
        id: 'files.move',
        summary: 'Move a file',
        method: 'POST',
        path: "_api/web/getfilebyserverrelativeurl('{path}')/moveto(newurl='{destination}',flags={flags})",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative source file path' },
          { name: 'destination', type: 'string', required: true, doc: 'Server-relative destination file path' },
          { name: 'flags', type: 'number', required: false, default: 1, doc: 'SharePoint move flags. 1 overwrites, 0 fails on conflict' },
        ],
        output: { envelope: envelopeSchema, data: 'Move status' },
        examples: ['sp-api files move --path "/sites/team/Shared Documents/a.txt" --destination "/sites/team/Shared Documents/b.txt"'],
      },
      copy: {
        id: 'files.copy',
        summary: 'Copy a file',
        method: 'POST',
        path: "_api/web/getfilebyserverrelativeurl('{path}')/copyto(strnewurl='{destination}',boverwrite={overwrite})",
        auth: 'required',
        handler: 'sharepoint-rest',
        requiresDigest: true,
        params: [
          { name: 'path', type: 'string', required: true, doc: 'Server-relative source file path' },
          { name: 'destination', type: 'string', required: true, doc: 'Server-relative destination file path' },
          { name: 'overwrite', type: 'boolean', required: false, default: true, doc: 'Whether SharePoint can overwrite an existing file' },
        ],
        output: { envelope: envelopeSchema, data: 'Copy status' },
        examples: ['sp-api files copy --path "/sites/team/Shared Documents/a.txt" --destination "/sites/team/Shared Documents/copy.txt"'],
      },
    },
  },
  schema: {
    id: 'schema',
    summary: 'Inspect the generated SharePoint capability schema',
    description: 'Return the machine-readable contract that also generates help and the skill router.',
    verbs: {
      show: {
        id: 'schema.show',
        summary: 'Show all capabilities or one capability/verb contract',
        method: 'LOCAL',
        auth: 'none',
        handler: 'schema',
        params: [
          { name: 'capability', type: 'string', required: false, doc: 'Capability id, for example lists or files' },
          { name: 'verb', type: 'string', required: false, doc: 'Verb id within the capability' },
        ],
        output: { envelope: envelopeSchema, data: 'Capability schema' },
        examples: ['sp-api schema', 'sp-api schema lists add-item'],
      },
    },
  },
  doctor: {
    id: 'doctor',
    summary: 'Run local health checks for the agentic CLI',
    description: 'Check scripts, auth file presence, and runtime compatibility.',
    verbs: {
      run: {
        id: 'doctor.run',
        summary: 'Run health checks',
        method: 'LOCAL',
        auth: 'none',
        handler: 'doctor',
        params: [],
        output: { envelope: envelopeSchema, data: 'Health-check results' },
        examples: ['sp-api doctor'],
      },
    },
  },
  update: {
    id: 'update',
    summary: 'Self-update this sp-api checkout',
    description: 'Pull latest source, install dependencies, and run the build validation for git-clone installs.',
    verbs: {
      run: {
        id: 'update.run',
        summary: 'Self-update from the current git clone',
        method: 'LOCAL',
        auth: 'none',
        handler: 'self-update',
        params: [],
        output: { envelope: envelopeSchema, data: 'Update steps and status' },
        examples: ['sp-api update'],
      },
    },
  },
};

const plannedCapabilities = {
  search: ['query', 'people'],
  pages: ['list', 'get', 'create', 'update', 'publish', 'delete'],
  users: ['list', 'get', 'me', 'ensure'],
  permissions: ['get', 'grant', 'revoke', 'break-inheritance', 'reset-inheritance'],
  sites: ['get', 'subsites', 'navigation'],
};

module.exports = { capabilities, plannedCapabilities, envelopeSchema };
